### PR TITLE
Url-encode password to prevent "XSS"

### PR DESCRIPTION
**Pull request by MatteoGheza**

### CODE REVIEW

**Comment by CyrisXD** [comment]
Hi there, sorry I missed this pull request. Is this still viable? I’m currently on vacation without a dev machine.

**Comment by MatteoGheza** [comment]
> Hi there, sorry I missed this pull request. Is this still viable? I’m currently on vacation without a dev machine. 

I removed this since I pushed this without noticing you, and I worked on a better fix.
Currently, the patch is submitted via huntr, so you can see it by going to https://huntr.dev/bounties/585590b9-81e4-4f76-b258-69d938004cf8/ (I wrote a security report and I added a better fix).
It's currently hidden, so you need to login with GitHub to prove that you are the maintainer of the project.

**Comment by CyrisXD** [comment]
Hi @MatteoGheza, I've logged in and confirmed it as valid. However it may just be missing something but I don't see the fix that side. I can only confirm a fix, by selecting a previously merged pull request. 

Cheers

**Comment by MatteoGheza** [comment]
> Hi @MatteoGheza, I've logged in and confirmed it as valid. However it may just be missing something but I don't see the fix that side. I can only confirm a fix, by selecting a previously merged pull request. 
> 
> Cheers

Thanks!
I opened a new PR with the updated fix. I tested this a lot and it seems to work.

**Pull request closed without merging**
